### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by GanitGenius** [mischov/meeseeks#41]
Hello, i'm getting below error during compilation using mix. I have included __{:meeseeks, "~> 0.9.2"}__ in my mix.exs deps and ran __{:meeseeks, "~> 0.9.2"}__.
Now running __mix compile__ gives this:

```
==> meeseeks_html5ever
Compiling NIF crate :meeseeks_html5ever_nif (native/meeseeks_html5ever_nif)...
could not compile dependency :meeseeks_html5ever, "mix compile" failed. You can recompile this dependency with "mix deps.compile meeseeks_html5ever", update it with "mix deps.update meeseeks_html5ever" or clean it with "mix deps.clean meeseeks_html5ever"
** (ErlangError) Erlang error: :enoent
    (elixir) lib/system.ex:622: System.cmd("cargo", ["rustc", "--no-default-features", "--release"], [cd: "/home/baldor/df/tph/deps/meeseeks_html5ever/native/meeseeks_html5ever_nif", stderr_to_stdout: true, env: [{"CARGO_TARGET_DIR", "/home/baldor/df/tph/_build/dev/rustler_crates/meeseeks_html5ever_nif"}], into: %IO.Stream{device: :standard_io, line_or_bytes: :line, raw: false}])
    lib/mix/tasks/compile.rustler.ex:51: Mix.Tasks.Compile.Rustler.compile_crate/1
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    lib/mix/tasks/compile.rustler.ex:14: Mix.Tasks.Compile.Rustler.run/1
    (mix) lib/mix/task.ex:314: Mix.Task.run_task/3
    (mix) lib/mix/tasks/compile.all.ex:63: Mix.Tasks.Compile.All.run_compiler/2
    (mix) lib/mix/tasks/compile.all.ex:47: Mix.Tasks.Compile.All.do_compile/4
    (mix) lib/mix/tasks/compile.all.ex:18: anonymous fn/1 in Mix.Tasks.Compile.All.run/1
```

**Comment by mischov** [comment]
I need to know what versions of Rust, Erlang/OTP, and Elixir you're using to try recreating the problem.

**Comment by GanitGenius** [comment]
sorry, I didn't have Rust installed earlier. 
Thanks,
